CREATE TABLE W_EMPLOYEE_D
(
  ROW_WID      INTEGER AUTO_INCREMENT,
  SID          VARCHAR(255) NOT NULL,
  DISPLAY_NAME VARCHAR(255) NOT NULL,
  DEPARTMENT   VARCHAR(255) NOT NULL,
  POSITION     VARCHAR(255),
  EMAIL        VARCHAR(255) NOT NULL,
  MANAGER      VARCHAR(255),
  CONSTRAINT EMPLOYEE_PK PRIMARY KEY (ROW_WID, SID)
);

CREATE TABLE CAMPAIGN
(
ID              INTEGER AUTO_INCREMENT,
  NAME          VARCHAR(255) NOT NULL,
  FILE_NAME     VARCHAR(255) NOT NULL,
  CREATED_BY    VARCHAR(255) NOT NULL,
  CREATED_DATE  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  ACTIVE        BOOLEAN,
  CONSTRAINT CAMPAIGN_PK PRIMARY KEY (ID, NAME)
);